services:
  - type: web
    name: telegram-bot
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: WEATHER_API_KEY
        value: deae5206758c44f38b0184151232208
